// Package datetime provides CLDR-based date/time formatting for Go, generated
// directly from the Unicode CLDR data (cldr-dates-full). It has ZERO external
// dependencies (standard-library time only) and is designed to match the
// behaviour of JavaScript's Intl.DateTimeFormat (and therefore fluent.js) for
// the dateStyle/timeStyle styles and the common component options.
//
// The symbol/pattern tables in tables_gen.go are produced by the generator in
// internal/gen. To regenerate them, run:
//
//	go generate ./cldr/datetime/...
//
// Usage:
//
//	out := datetime.Format("en", t, datetime.Options{DateStyle: "long", TimeStyle: "short"})
package datetime

import (
	"strings"
	"time"
)

// The generator reads its CLDR input base from the CLDR_DATA environment
// variable (a node_modules tree), falling back to the checked-in .reference
// copy when unset. Both the Go tables and the Node-produced golden fixtures are
// regenerated by `go generate ./cldr/datetime/...`.
//go:generate go run ./internal/gen/main.go -out tables_gen.go
//go:generate sh -c "node internal/gen/fixtures.js > testdata/intl_dates.json"

// Options mirrors the subset of Intl.DateTimeFormatOptions that fluent.js uses.
// It intentionally mirrors the field names of fluent.DateTimeOptions in the
// core package (without importing it). Empty strings / nil pointers mean
// "unset".
type Options struct {
	Hour12                 *bool
	Weekday                string // "long" | "short" | "narrow"
	Era                    string // "long" | "short" | "narrow"
	Year                   string // "numeric" | "2-digit"
	Month                  string // "numeric" | "2-digit" | "long" | "short" | "narrow"
	Day                    string // "numeric" | "2-digit"
	Hour                   string // "numeric" | "2-digit"
	Minute                 string // "numeric" | "2-digit"
	Second                 string // "numeric" | "2-digit"
	TimeZoneName           string // "long" | "short"
	DateStyle              string // "full" | "long" | "medium" | "short"
	TimeStyle              string // "full" | "long" | "medium" | "short"
	DayPeriod              string // "narrow" | "short" | "long"
	FractionalSecondDigits *int   // 1..3
	Calendar               string // only "gregory"/"gregorian" supported
	NumberingSystem        string // overrides the locale default
	TimeZone               string // IANA name; defaults to local
}

// localeData holds the resolved CLDR symbol tables and patterns for one locale.
// The concrete values are emitted into tables_gen.go by the generator.
type localeData struct {
	MonthsFormat map[string][]string
	MonthsStand  map[string][]string
	DaysFormat   map[string][]string
	DaysStand    map[string][]string
	QuartersFmt  map[string][]string
	QuartersStd  map[string][]string

	DayPeriodsFmt map[string]map[string]string
	DayPeriodsStd map[string]map[string]string
	Eras          map[string][]string

	DateFormats map[string]string
	TimeFormats map[string]string
	DateTime    map[string]string
	AtTime      map[string]string
	Available   map[string]string

	NumberingSystem string
	Zones           map[string]string

	// DayPeriodRules maps a flexible day-period key (morning1, afternoon1,
	// evening1, night1, noon, midnight) to its time range. For a half-open
	// range [from,before) the value is {from, before}; for an exact-point rule
	// (_at, used by noon/midnight) from==before==the point. Times are minutes
	// since 00:00 (0..1440). A range may wrap past midnight (from > before).
	DayPeriodRules map[string][2]int

	// MetazoneNames maps a CLDR metazone id (e.g. "America_Eastern") to its
	// localized names, keyed "<width>.<type>" where width is long|short and
	// type is generic|standard|daylight (e.g. "long.daylight"). Only the
	// sub-keys present in CLDR are emitted.
	MetazoneNames map[string]map[string]string

	// ZoneOverrides maps a CLDR zone id (legacy IANA key, '/'-joined, e.g.
	// "Europe/London") to per-zone name overrides, same "<width>.<type>" keys
	// as MetazoneNames. These take priority over the metazone names.
	ZoneOverrides map[string]map[string]string

	// ExemplarCities maps a CLDR zone id to its localized exemplar city
	// (feeds the regionFormat location fallback for generic names).
	ExemplarCities map[string]string

	// TerritoryNames maps a territory code (e.g. "GB") to its localized display
	// name, limited to the country-representative territories. Used by the
	// generic-location format ("United Kingdom Time").
	TerritoryNames map[string]string
}

// resolveLocale walks the CLDR fallback chain to find a locale present in the
// generated table: exact id -> explicit parentLocale -> truncate trailing
// subtag -> "en" as the ultimate root substitute.
func resolveLocale(locale string) (*localeData, string) {
	cur := normalizeLocale(locale)
	seen := map[string]bool{}
	for cur != "" && cur != "und" && !seen[cur] {
		seen[cur] = true
		if idx, ok := localeIndex[cur]; ok {
			return &localeBlobs[idx], cur
		}
		if p, ok := parentLocaleMap[cur]; ok {
			cur = p
			continue
		}
		if i := strings.LastIndexByte(cur, '-'); i >= 0 {
			cur = cur[:i]
			continue
		}
		break
	}
	// ultimate fallback
	if idx, ok := localeIndex["en"]; ok {
		return &localeBlobs[idx], "en"
	}
	return nil, ""
}

// normalizeLocale lowercases language/region tags into CLDR's '-' form while
// keeping script subtags title-cased the way CLDR keys them (e.g. zh-Hant).
func normalizeLocale(locale string) string {
	locale = strings.ReplaceAll(locale, "_", "-")
	parts := strings.Split(locale, "-")
	for i, p := range parts {
		switch {
		case i == 0:
			parts[i] = strings.ToLower(p)
		case len(p) == 4:
			// script: Titlecase
			parts[i] = strings.ToUpper(p[:1]) + strings.ToLower(p[1:])
		case len(p) == 2:
			// region: uppercase
			parts[i] = strings.ToUpper(p)
		default:
			parts[i] = strings.ToLower(p)
		}
	}
	return strings.Join(parts, "-")
}

// Format renders t for the given locale according to opts, matching
// Intl.DateTimeFormat semantics for dateStyle/timeStyle and common component
// options. The locale is a BCP-47 string; unknown locales fall back through the
// CLDR parent chain to en.
func Format(locale string, t time.Time, opts Options) string {
	ld, resolved := resolveLocale(locale)
	if ld == nil {
		return t.Format(time.RFC3339)
	}

	// Apply timeZone.
	zoneID := ""
	canonicalZone := ""
	observesDST := false
	if opts.TimeZone != "" {
		if loc, err := time.LoadLocation(opts.TimeZone); err == nil {
			t = t.In(loc)
			canonicalZone = opts.TimeZone
			zoneID = cldrZoneID(opts.TimeZone)
			observesDST = zoneObservesDST(t)
		}
	}

	// Numbering system: option overrides locale default.
	ns := opts.NumberingSystem
	if ns == "" {
		ns = ld.NumberingSystem
	}
	digits := numberingSystemDigits[ns]

	ctx := &formatCtx{ld: ld, locale: resolved, digits: digits, opts: opts, zoneID: zoneID, canonicalZone: canonicalZone, zoneObservesDST: observesDST}

	pattern := ctx.resolvePattern()
	out := ctx.interpret(pattern, t)
	// node/ICU normalizes the narrow no-break space (U+202F) that recent CLDR
	// data places before day periods back to a regular space; mirror that so we
	// match Intl output. The regular no-break space (U+00A0) is preserved.
	return strings.ReplaceAll(out, " ", " ")
}

// resolvePattern selects the CLDR pattern string to interpret based on opts.
func (c *formatCtx) resolvePattern() string {
	o := c.opts
	hasDate := o.DateStyle != ""
	hasTime := o.TimeStyle != ""

	if hasDate || hasTime {
		var datePat, timePat string
		if hasDate {
			datePat = c.ld.DateFormats[o.DateStyle]
		}
		if hasTime {
			// ICU pads a single-digit hour to two digits when the caller forces a
			// 24-hour clock onto a locale that defaults to a 12-hour clock (e.g. en
			// timeStyle:"short" + hour12:false -> "09:07"). The reverse stays as the
			// pattern's own width. This mirrors the component path below.
			if o.Hour12 != nil && !*o.Hour12 && c.localeUses12() {
				c.padNumericHour = true
			}
			timePat = c.ld.TimeFormats[o.TimeStyle]
			timePat = c.applyHourCycle(timePat)
		}
		switch {
		case hasDate && hasTime:
			// Intl combines via dateTimeFormats-atTime, keyed by dateStyle.
			combiner := c.ld.AtTime[o.DateStyle]
			if combiner == "" {
				combiner = c.ld.DateTime[o.DateStyle]
			}
			return combine(combiner, datePat, timePat)
		case hasDate:
			return datePat
		default:
			return timePat
		}
	}

	// ICU renders a "numeric" hour padded to two digits when the caller forces a
	// 24-hour clock onto a locale that defaults to a 12-hour clock (e.g. en with
	// hour12:false -> "09:07"). The reverse (forcing 12-hour onto a 24-hour
	// locale) stays unpadded. Detect that asymmetric case here.
	if o.Hour == "numeric" && o.Hour12 != nil && !*o.Hour12 && c.localeUses12() {
		c.padNumericHour = true
	}

	// ICU keeps a "numeric" hour padded to two digits when the resolved 24-hour
	// pattern (HH) also carries a zone name but NO seconds (e.g. de "09:07 UTC").
	// adjustWidths applies this only to 24-hour hour letters.
	if o.Hour == "numeric" && o.TimeZoneName != "" && o.Second == "" {
		c.zoneNoSecPad = true
	}

	// Component options -> build skeleton, best-match against availableFormats.
	skel := c.buildSkeleton()
	if skel == "" {
		// No options at all: Intl defaults to numeric y/M/d.
		skel = "yMd"
	}
	pat := c.bestMatch(skel)
	pat = c.applyHourCycle(pat)
	// Specific (z) and offset (O/X/Z) zone names attach to the time with a plain
	// space when NO seconds are shown. CLDR's only zone-bearing availableFormats
	// are generic (v/vvvv); a few locales separate them with a comma (e.g. cs
	// "H:mm, vvvv"), which Intl keeps for generic names and for the with-seconds
	// specific pattern, but replaces with a space for the without-seconds
	// specific/offset case. Normalize only that case.
	if o.Second == "" {
		switch o.TimeZoneName {
		case "short", "long", "shortOffset", "longOffset":
			pat = normalizeZoneSeparator(pat)
		}
	}
	// fractionalSecondDigits never appears in availableFormats, so best-fit /
	// synthesis never carries the S field into the resolved pattern. Mirror ICU's
	// adjustFieldTypes by injecting the fractional-second field adjacent to the
	// seconds field after matching.
	if o.FractionalSecondDigits != nil && *o.FractionalSecondDigits > 0 {
		pat = injectFractionalSecond(pat, *o.FractionalSecondDigits)
	}
	return pat
}

// injectFractionalSecond places a decimal separator and an S-run immediately
// after the seconds field of pattern, matching ICU's adjustFieldTypes. The "."
// literal is the CLDR convention; ICU substitutes the locale decimal separator
// at format time. We do not have the decimal-separator table here, so locales
// whose decimal separator is not "." (e.g. fr uses ",") are not yet exact.
// TODO: thread the locale decimal separator (from cldr/number) through to here.
func injectFractionalSecond(pattern string, digits int) string {
	runes := []rune(pattern)
	n := len(runes)
	inQuote := false
	// Find the end of the last unquoted seconds run.
	end := -1
	for i := 0; i < n; i++ {
		ch := runes[i]
		if ch == '\'' {
			inQuote = !inQuote
			continue
		}
		if !inQuote && ch == 's' {
			j := i
			for j < n && runes[j] == 's' {
				j++
			}
			end = j
			i = j - 1
		}
	}
	if end < 0 {
		return pattern
	}
	frac := "." + strings.Repeat("S", digits)
	return string(runes[:end]) + frac + string(runes[end:])
}

// combine substitutes {1}=date and {0}=time into a CLDR combiner pattern,
// honoring single-quoted literals in the combiner.
func combine(combiner, datePat, timePat string) string {
	if combiner == "" {
		return strings.TrimSpace(datePat + " " + timePat)
	}
	var b strings.Builder
	inQuote := false
	runes := []rune(combiner)
	for i := 0; i < len(runes); i++ {
		ch := runes[i]
		if ch == '\'' {
			// Keep quote markers verbatim so the interpreter treats the literal
			// segment as a literal too.
			inQuote = !inQuote
			b.WriteRune(ch)
			continue
		}
		if !inQuote && ch == '{' && i+2 < len(runes) && runes[i+2] == '}' {
			switch runes[i+1] {
			case '0':
				b.WriteString(timePat)
				i += 2
				continue
			case '1':
				b.WriteString(datePat)
				i += 2
				continue
			}
		}
		b.WriteRune(ch)
	}
	return b.String()
}
