// Code generated by internal/gen; DO NOT EDIT.
// Source: Unicode CLDR plurals.json / ordinals.json.

package plural

var cardinalSet0 = &ruleSet{
	cats: []Category{One, Other},
	preds: []rule{
		func(o Operands) bool { return o.N == 1.0 },
	},
}

var cardinalSet1 = &ruleSet{
	cats: []Category{One, Other},
	preds: []rule{
		func(o Operands) bool { return inRangeN(o.N, 0, 1) },
	},
}

var cardinalSet2 = &ruleSet{
	cats: []Category{One, Other},
	preds: []rule{
		func(o Operands) bool { return o.I == 0 || o.N == 1.0 },
	},
}

var cardinalSet3 = &ruleSet{
	cats: []Category{Zero, One, Two, Few, Many, Other},
	preds: []rule{
		func(o Operands) bool { return o.N == 0.0 },
		func(o Operands) bool { return o.N == 1.0 },
		func(o Operands) bool { return o.N == 2.0 },
		func(o Operands) bool { return inRangeN(modNf(o.N, 100), 3, 10) },
		func(o Operands) bool { return inRangeN(modNf(o.N, 100), 11, 99) },
	},
}

var cardinalSet4 = &ruleSet{
	cats: []Category{One, Other},
	preds: []rule{
		func(o Operands) bool { return (o.I == 1 && o.V == 0) },
	},
}

var cardinalSet5 = &ruleSet{
	cats: []Category{One, Few, Many, Other},
	preds: []rule{
		func(o Operands) bool { return (modNf(o.N, 10) == 1.0 && !(modNf(o.N, 100) == 11.0)) },
		func(o Operands) bool { return (inRangeN(modNf(o.N, 10), 2, 4) && !(inRangeN(modNf(o.N, 100), 12, 14))) },
		func(o Operands) bool {
			return modNf(o.N, 10) == 0.0 || inRangeN(modNf(o.N, 10), 5, 9) || inRangeN(modNf(o.N, 100), 11, 14)
		},
	},
}

var cardinalSet6 = &ruleSet{
	cats: []Category{Zero, One, Other},
	preds: []rule{
		func(o Operands) bool { return o.N == 0.0 },
		func(o Operands) bool { return o.N == 1.0 },
	},
}

var cardinalSet7 = &ruleSet{
	cats:  []Category{Other},
	preds: []rule{},
}

var cardinalSet8 = &ruleSet{
	cats: []Category{One, Two, Few, Many, Other},
	preds: []rule{
		func(o Operands) bool {
			return (modNf(o.N, 10) == 1.0 && !(modNf(o.N, 100) == 11.0 || modNf(o.N, 100) == 71.0 || modNf(o.N, 100) == 91.0))
		},
		func(o Operands) bool {
			return (modNf(o.N, 10) == 2.0 && !(modNf(o.N, 100) == 12.0 || modNf(o.N, 100) == 72.0 || modNf(o.N, 100) == 92.0))
		},
		func(o Operands) bool {
			return ((inRangeN(modNf(o.N, 10), 3, 4) || modNf(o.N, 10) == 9.0) && !(inRangeN(modNf(o.N, 100), 10, 19) || inRangeN(modNf(o.N, 100), 70, 79) || inRangeN(modNf(o.N, 100), 90, 99)))
		},
		func(o Operands) bool { return (!(o.N == 0.0) && modNf(o.N, 1000000) == 0.0) },
	},
}

var cardinalSet9 = &ruleSet{
	cats: []Category{One, Few, Other},
	preds: []rule{
		func(o Operands) bool {
			return (o.V == 0 && o.I%10 == 1 && !(o.I%100 == 11)) || (o.F%10 == 1 && !(o.F%100 == 11))
		},
		func(o Operands) bool {
			return (o.V == 0 && o.I%10 >= 2 && o.I%10 <= 4 && !(o.I%100 >= 12 && o.I%100 <= 14)) || (o.F%10 >= 2 && o.F%10 <= 4 && !(o.F%100 >= 12 && o.F%100 <= 14))
		},
	},
}

var cardinalSet10 = &ruleSet{
	cats: []Category{One, Many, Other},
	preds: []rule{
		func(o Operands) bool { return (o.I == 1 && o.V == 0) },
		func(o Operands) bool {
			return (o.C == 0 && !(o.I == 0) && o.I%1000000 == 0 && o.V == 0) || !(o.C >= 0 && o.C <= 5)
		},
	},
}

var cardinalSet11 = &ruleSet{
	cats: []Category{One, Other},
	preds: []rule{
		func(o Operands) bool {
			return (o.V == 0 && (o.I == 1 || o.I == 2 || o.I == 3)) || (o.V == 0 && !(o.I%10 == 4 || o.I%10 == 6 || o.I%10 == 9)) || (!(o.V == 0) && !(o.F%10 == 4 || o.F%10 == 6 || o.F%10 == 9))
		},
	},
}

var cardinalSet12 = &ruleSet{
	cats: []Category{One, Few, Many, Other},
	preds: []rule{
		func(o Operands) bool { return (o.I == 1 && o.V == 0) },
		func(o Operands) bool { return (o.I >= 2 && o.I <= 4 && o.V == 0) },
		func(o Operands) bool { return !(o.V == 0) },
	},
}

var cardinalSet13 = &ruleSet{
	cats: []Category{Zero, One, Two, Few, Many, Other},
	preds: []rule{
		func(o Operands) bool { return o.N == 0.0 },
		func(o Operands) bool { return o.N == 1.0 },
		func(o Operands) bool { return o.N == 2.0 },
		func(o Operands) bool { return o.N == 3.0 },
		func(o Operands) bool { return o.N == 6.0 },
	},
}

var cardinalSet14 = &ruleSet{
	cats: []Category{One, Other},
	preds: []rule{
		func(o Operands) bool { return o.N == 1.0 || (!(o.T == 0) && (o.I == 0 || o.I == 1)) },
	},
}

var cardinalSet15 = &ruleSet{
	cats: []Category{One, Two, Few, Other},
	preds: []rule{
		func(o Operands) bool { return (o.V == 0 && o.I%100 == 1) || o.F%100 == 1 },
		func(o Operands) bool { return (o.V == 0 && o.I%100 == 2) || o.F%100 == 2 },
		func(o Operands) bool {
			return (o.V == 0 && o.I%100 >= 3 && o.I%100 <= 4) || o.F%100 >= 3 && o.F%100 <= 4
		},
	},
}

var cardinalSet16 = &ruleSet{
	cats: []Category{One, Many, Other},
	preds: []rule{
		func(o Operands) bool { return o.N == 1.0 },
		func(o Operands) bool {
			return (o.C == 0 && !(o.I == 0) && o.I%1000000 == 0 && o.V == 0) || !(o.C >= 0 && o.C <= 5)
		},
	},
}

var cardinalSet17 = &ruleSet{
	cats: []Category{One, Other},
	preds: []rule{
		func(o Operands) bool { return (o.I == 0 || o.I == 1) },
	},
}

var cardinalSet18 = &ruleSet{
	cats: []Category{One, Many, Other},
	preds: []rule{
		func(o Operands) bool { return (o.I == 0 || o.I == 1) },
		func(o Operands) bool {
			return (o.C == 0 && !(o.I == 0) && o.I%1000000 == 0 && o.V == 0) || !(o.C >= 0 && o.C <= 5)
		},
	},
}

var cardinalSet19 = &ruleSet{
	cats: []Category{One, Two, Few, Many, Other},
	preds: []rule{
		func(o Operands) bool { return o.N == 1.0 },
		func(o Operands) bool { return o.N == 2.0 },
		func(o Operands) bool { return inRangeN(o.N, 3, 6) },
		func(o Operands) bool { return inRangeN(o.N, 7, 10) },
	},
}

var cardinalSet20 = &ruleSet{
	cats: []Category{One, Two, Few, Other},
	preds: []rule{
		func(o Operands) bool { return (o.N == 1.0 || o.N == 11.0) },
		func(o Operands) bool { return (o.N == 2.0 || o.N == 12.0) },
		func(o Operands) bool { return (inRangeN(o.N, 3, 10) || inRangeN(o.N, 13, 19)) },
	},
}

var cardinalSet21 = &ruleSet{
	cats: []Category{One, Two, Few, Many, Other},
	preds: []rule{
		func(o Operands) bool { return (o.V == 0 && o.I%10 == 1) },
		func(o Operands) bool { return (o.V == 0 && o.I%10 == 2) },
		func(o Operands) bool {
			return (o.V == 0 && (o.I%100 == 0 || o.I%100 == 20 || o.I%100 == 40 || o.I%100 == 60 || o.I%100 == 80))
		},
		func(o Operands) bool { return !(o.V == 0) },
	},
}

var cardinalSet22 = &ruleSet{
	cats: []Category{One, Two, Other},
	preds: []rule{
		func(o Operands) bool { return (o.I == 1 && o.V == 0) || (o.I == 0 && !(o.V == 0)) },
		func(o Operands) bool { return (o.I == 2 && o.V == 0) },
	},
}

var cardinalSet23 = &ruleSet{
	cats: []Category{One, Other},
	preds: []rule{
		func(o Operands) bool {
			return (o.T == 0 && o.I%10 == 1 && !(o.I%100 == 11)) || (o.T%10 == 1 && !(o.T%100 == 11))
		},
	},
}

var cardinalSet24 = &ruleSet{
	cats: []Category{One, Two, Other},
	preds: []rule{
		func(o Operands) bool { return o.N == 1.0 },
		func(o Operands) bool { return o.N == 2.0 },
	},
}

var cardinalSet25 = &ruleSet{
	cats: []Category{Zero, One, Two, Few, Many, Other},
	preds: []rule{
		func(o Operands) bool { return o.N == 0.0 },
		func(o Operands) bool { return o.N == 1.0 },
		func(o Operands) bool {
			return (modNf(o.N, 100) == 2.0 || modNf(o.N, 100) == 22.0 || modNf(o.N, 100) == 42.0 || modNf(o.N, 100) == 62.0 || modNf(o.N, 100) == 82.0) || (modNf(o.N, 1000) == 0.0 && (inRangeN(modNf(o.N, 100000), 1000, 20000) || modNf(o.N, 100000) == 40000.0 || modNf(o.N, 100000) == 60000.0 || modNf(o.N, 100000) == 80000.0)) || (!(o.N == 0.0) && modNf(o.N, 1000000) == 100000.0)
		},
		func(o Operands) bool {
			return (modNf(o.N, 100) == 3.0 || modNf(o.N, 100) == 23.0 || modNf(o.N, 100) == 43.0 || modNf(o.N, 100) == 63.0 || modNf(o.N, 100) == 83.0)
		},
		func(o Operands) bool {
			return (!(o.N == 1.0) && (modNf(o.N, 100) == 1.0 || modNf(o.N, 100) == 21.0 || modNf(o.N, 100) == 41.0 || modNf(o.N, 100) == 61.0 || modNf(o.N, 100) == 81.0))
		},
	},
}

var cardinalSet26 = &ruleSet{
	cats: []Category{Zero, One, Other},
	preds: []rule{
		func(o Operands) bool { return o.N == 0.0 },
		func(o Operands) bool { return ((o.I == 0 || o.I == 1) && !(o.N == 0.0)) },
	},
}

var cardinalSet27 = &ruleSet{
	cats: []Category{One, Few, Many, Other},
	preds: []rule{
		func(o Operands) bool { return (modNf(o.N, 10) == 1.0 && !(inRangeN(modNf(o.N, 100), 11, 19))) },
		func(o Operands) bool { return (inRangeN(modNf(o.N, 10), 2, 9) && !(inRangeN(modNf(o.N, 100), 11, 19))) },
		func(o Operands) bool { return !(o.F == 0) },
	},
}

var cardinalSet28 = &ruleSet{
	cats: []Category{Zero, One, Other},
	preds: []rule{
		func(o Operands) bool {
			return modNf(o.N, 10) == 0.0 || inRangeN(modNf(o.N, 100), 11, 19) || (o.V == 2 && o.F%100 >= 11 && o.F%100 <= 19)
		},
		func(o Operands) bool {
			return (modNf(o.N, 10) == 1.0 && !(modNf(o.N, 100) == 11.0)) || (o.V == 2 && o.F%10 == 1 && !(o.F%100 == 11)) || (!(o.V == 2) && o.F%10 == 1)
		},
	},
}

var cardinalSet29 = &ruleSet{
	cats: []Category{One, Other},
	preds: []rule{
		func(o Operands) bool {
			return (o.V == 0 && o.I%10 == 1 && !(o.I%100 == 11)) || (o.F%10 == 1 && !(o.F%100 == 11))
		},
	},
}

var cardinalSet30 = &ruleSet{
	cats: []Category{One, Few, Other},
	preds: []rule{
		func(o Operands) bool { return (o.I == 1 && o.V == 0) },
		func(o Operands) bool {
			return !(o.V == 0) || o.N == 0.0 || (!(o.N == 1.0) && inRangeN(modNf(o.N, 100), 1, 19))
		},
	},
}

var cardinalSet31 = &ruleSet{
	cats: []Category{One, Two, Few, Many, Other},
	preds: []rule{
		func(o Operands) bool { return o.N == 1.0 },
		func(o Operands) bool { return o.N == 2.0 },
		func(o Operands) bool { return o.N == 0.0 || inRangeN(modNf(o.N, 100), 3, 10) },
		func(o Operands) bool { return inRangeN(modNf(o.N, 100), 11, 19) },
	},
}

var cardinalSet32 = &ruleSet{
	cats: []Category{One, Few, Many, Other},
	preds: []rule{
		func(o Operands) bool { return (o.I == 1 && o.V == 0) },
		func(o Operands) bool {
			return (o.V == 0 && o.I%10 >= 2 && o.I%10 <= 4 && !(o.I%100 >= 12 && o.I%100 <= 14))
		},
		func(o Operands) bool {
			return (o.V == 0 && !(o.I == 1) && o.I%10 >= 0 && o.I%10 <= 1) || (o.V == 0 && o.I%10 >= 5 && o.I%10 <= 9) || (o.V == 0 && o.I%100 >= 12 && o.I%100 <= 14)
		},
	},
}

var cardinalSet33 = &ruleSet{
	cats: []Category{One, Many, Other},
	preds: []rule{
		func(o Operands) bool { return o.I >= 0 && o.I <= 1 },
		func(o Operands) bool {
			return (o.C == 0 && !(o.I == 0) && o.I%1000000 == 0 && o.V == 0) || !(o.C >= 0 && o.C <= 5)
		},
	},
}

var cardinalSet34 = &ruleSet{
	cats: []Category{One, Few, Many, Other},
	preds: []rule{
		func(o Operands) bool { return (o.V == 0 && o.I%10 == 1 && !(o.I%100 == 11)) },
		func(o Operands) bool {
			return (o.V == 0 && o.I%10 >= 2 && o.I%10 <= 4 && !(o.I%100 >= 12 && o.I%100 <= 14))
		},
		func(o Operands) bool {
			return (o.V == 0 && o.I%10 == 0) || (o.V == 0 && o.I%10 >= 5 && o.I%10 <= 9) || (o.V == 0 && o.I%100 >= 11 && o.I%100 <= 14)
		},
	},
}

var cardinalSet35 = &ruleSet{
	cats: []Category{One, Few, Other},
	preds: []rule{
		func(o Operands) bool { return o.I == 0 || o.N == 1.0 },
		func(o Operands) bool { return inRangeN(o.N, 2, 10) },
	},
}

var cardinalSet36 = &ruleSet{
	cats: []Category{One, Other},
	preds: []rule{
		func(o Operands) bool { return (o.N == 0.0 || o.N == 1.0) || (o.I == 0 && o.F == 1) },
	},
}

var cardinalSet37 = &ruleSet{
	cats: []Category{One, Two, Few, Other},
	preds: []rule{
		func(o Operands) bool { return (o.V == 0 && o.I%100 == 1) },
		func(o Operands) bool { return (o.V == 0 && o.I%100 == 2) },
		func(o Operands) bool { return (o.V == 0 && o.I%100 >= 3 && o.I%100 <= 4) || !(o.V == 0) },
	},
}

var cardinalSet38 = &ruleSet{
	cats: []Category{One, Other},
	preds: []rule{
		func(o Operands) bool { return inRangeN(o.N, 0, 1) || inRangeN(o.N, 11, 99) },
	},
}

var cardinalRules = map[string]*ruleSet{
	"af":    cardinalSet0,
	"ak":    cardinalSet1,
	"am":    cardinalSet2,
	"an":    cardinalSet0,
	"ar":    cardinalSet3,
	"ars":   cardinalSet3,
	"as":    cardinalSet2,
	"asa":   cardinalSet0,
	"ast":   cardinalSet4,
	"az":    cardinalSet0,
	"bal":   cardinalSet0,
	"be":    cardinalSet5,
	"bem":   cardinalSet0,
	"bez":   cardinalSet0,
	"bg":    cardinalSet0,
	"bho":   cardinalSet1,
	"blo":   cardinalSet6,
	"bm":    cardinalSet7,
	"bn":    cardinalSet2,
	"bo":    cardinalSet7,
	"br":    cardinalSet8,
	"brx":   cardinalSet0,
	"bs":    cardinalSet9,
	"ca":    cardinalSet10,
	"ce":    cardinalSet0,
	"ceb":   cardinalSet11,
	"cgg":   cardinalSet0,
	"chr":   cardinalSet0,
	"ckb":   cardinalSet0,
	"cs":    cardinalSet12,
	"cy":    cardinalSet13,
	"da":    cardinalSet14,
	"de":    cardinalSet4,
	"doi":   cardinalSet2,
	"dsb":   cardinalSet15,
	"dv":    cardinalSet0,
	"dz":    cardinalSet7,
	"ee":    cardinalSet0,
	"el":    cardinalSet0,
	"en":    cardinalSet4,
	"eo":    cardinalSet0,
	"es":    cardinalSet16,
	"et":    cardinalSet4,
	"eu":    cardinalSet0,
	"fa":    cardinalSet2,
	"ff":    cardinalSet17,
	"fi":    cardinalSet4,
	"fil":   cardinalSet11,
	"fo":    cardinalSet0,
	"fr":    cardinalSet18,
	"fur":   cardinalSet0,
	"fy":    cardinalSet4,
	"ga":    cardinalSet19,
	"gd":    cardinalSet20,
	"gl":    cardinalSet4,
	"gsw":   cardinalSet0,
	"gu":    cardinalSet2,
	"guw":   cardinalSet1,
	"gv":    cardinalSet21,
	"ha":    cardinalSet0,
	"haw":   cardinalSet0,
	"he":    cardinalSet22,
	"hi":    cardinalSet2,
	"hnj":   cardinalSet7,
	"hr":    cardinalSet9,
	"hsb":   cardinalSet15,
	"hu":    cardinalSet0,
	"hy":    cardinalSet17,
	"ia":    cardinalSet4,
	"id":    cardinalSet7,
	"ig":    cardinalSet7,
	"ii":    cardinalSet7,
	"io":    cardinalSet4,
	"is":    cardinalSet23,
	"it":    cardinalSet10,
	"iu":    cardinalSet24,
	"ja":    cardinalSet7,
	"jbo":   cardinalSet7,
	"jgo":   cardinalSet0,
	"jmc":   cardinalSet0,
	"jv":    cardinalSet7,
	"jw":    cardinalSet7,
	"ka":    cardinalSet0,
	"kab":   cardinalSet17,
	"kaj":   cardinalSet0,
	"kcg":   cardinalSet0,
	"kde":   cardinalSet7,
	"kea":   cardinalSet7,
	"kk":    cardinalSet0,
	"kkj":   cardinalSet0,
	"kl":    cardinalSet0,
	"km":    cardinalSet7,
	"kn":    cardinalSet2,
	"ko":    cardinalSet7,
	"ks":    cardinalSet0,
	"ksb":   cardinalSet0,
	"ksh":   cardinalSet6,
	"ku":    cardinalSet0,
	"kw":    cardinalSet25,
	"ky":    cardinalSet0,
	"lag":   cardinalSet26,
	"lb":    cardinalSet0,
	"lg":    cardinalSet0,
	"lij":   cardinalSet4,
	"lkt":   cardinalSet7,
	"ln":    cardinalSet1,
	"lo":    cardinalSet7,
	"lt":    cardinalSet27,
	"lv":    cardinalSet28,
	"mas":   cardinalSet0,
	"mg":    cardinalSet1,
	"mgo":   cardinalSet0,
	"mk":    cardinalSet29,
	"ml":    cardinalSet0,
	"mn":    cardinalSet0,
	"mo":    cardinalSet30,
	"mr":    cardinalSet0,
	"ms":    cardinalSet7,
	"mt":    cardinalSet31,
	"my":    cardinalSet7,
	"nah":   cardinalSet0,
	"naq":   cardinalSet24,
	"nb":    cardinalSet0,
	"nd":    cardinalSet0,
	"ne":    cardinalSet0,
	"nl":    cardinalSet4,
	"nn":    cardinalSet0,
	"nnh":   cardinalSet0,
	"no":    cardinalSet0,
	"nqo":   cardinalSet7,
	"nr":    cardinalSet0,
	"nso":   cardinalSet1,
	"ny":    cardinalSet0,
	"nyn":   cardinalSet0,
	"om":    cardinalSet0,
	"or":    cardinalSet0,
	"os":    cardinalSet0,
	"osa":   cardinalSet7,
	"pa":    cardinalSet1,
	"pap":   cardinalSet0,
	"pcm":   cardinalSet2,
	"pl":    cardinalSet32,
	"prg":   cardinalSet28,
	"ps":    cardinalSet0,
	"pt":    cardinalSet33,
	"pt-PT": cardinalSet10,
	"rm":    cardinalSet0,
	"ro":    cardinalSet30,
	"rof":   cardinalSet0,
	"ru":    cardinalSet34,
	"rwk":   cardinalSet0,
	"sah":   cardinalSet7,
	"saq":   cardinalSet0,
	"sat":   cardinalSet24,
	"sc":    cardinalSet4,
	"scn":   cardinalSet4,
	"sd":    cardinalSet0,
	"sdh":   cardinalSet0,
	"se":    cardinalSet24,
	"seh":   cardinalSet0,
	"ses":   cardinalSet7,
	"sg":    cardinalSet7,
	"sh":    cardinalSet9,
	"shi":   cardinalSet35,
	"si":    cardinalSet36,
	"sk":    cardinalSet12,
	"sl":    cardinalSet37,
	"sma":   cardinalSet24,
	"smi":   cardinalSet24,
	"smj":   cardinalSet24,
	"smn":   cardinalSet24,
	"sms":   cardinalSet24,
	"sn":    cardinalSet0,
	"so":    cardinalSet0,
	"sq":    cardinalSet0,
	"sr":    cardinalSet9,
	"ss":    cardinalSet0,
	"ssy":   cardinalSet0,
	"st":    cardinalSet0,
	"su":    cardinalSet7,
	"sv":    cardinalSet4,
	"sw":    cardinalSet4,
	"syr":   cardinalSet0,
	"ta":    cardinalSet0,
	"te":    cardinalSet0,
	"teo":   cardinalSet0,
	"th":    cardinalSet7,
	"ti":    cardinalSet1,
	"tig":   cardinalSet0,
	"tk":    cardinalSet0,
	"tl":    cardinalSet11,
	"tn":    cardinalSet0,
	"to":    cardinalSet7,
	"tpi":   cardinalSet7,
	"tr":    cardinalSet0,
	"ts":    cardinalSet0,
	"tzm":   cardinalSet38,
	"ug":    cardinalSet0,
	"uk":    cardinalSet34,
	"und":   cardinalSet7,
	"ur":    cardinalSet4,
	"uz":    cardinalSet0,
	"ve":    cardinalSet0,
	"vec":   cardinalSet10,
	"vi":    cardinalSet7,
	"vo":    cardinalSet0,
	"vun":   cardinalSet0,
	"wa":    cardinalSet1,
	"wae":   cardinalSet0,
	"wo":    cardinalSet7,
	"xh":    cardinalSet0,
	"xog":   cardinalSet0,
	"yi":    cardinalSet4,
	"yo":    cardinalSet7,
	"yue":   cardinalSet7,
	"zh":    cardinalSet7,
	"zu":    cardinalSet2,
}

var ordinalSet0 = &ruleSet{
	cats:  []Category{Other},
	preds: []rule{},
}

var ordinalSet1 = &ruleSet{
	cats: []Category{One, Two, Few, Many, Other},
	preds: []rule{
		func(o Operands) bool {
			return (o.N == 1.0 || o.N == 5.0 || o.N == 7.0 || o.N == 8.0 || o.N == 9.0 || o.N == 10.0)
		},
		func(o Operands) bool { return (o.N == 2.0 || o.N == 3.0) },
		func(o Operands) bool { return o.N == 4.0 },
		func(o Operands) bool { return o.N == 6.0 },
	},
}

var ordinalSet2 = &ruleSet{
	cats: []Category{One, Few, Many, Other},
	preds: []rule{
		func(o Operands) bool {
			return (o.I%10 == 1 || o.I%10 == 2 || o.I%10 == 5 || o.I%10 == 7 || o.I%10 == 8) || (o.I%100 == 20 || o.I%100 == 50 || o.I%100 == 70 || o.I%100 == 80)
		},
		func(o Operands) bool {
			return (o.I%10 == 3 || o.I%10 == 4) || (o.I%1000 == 100 || o.I%1000 == 200 || o.I%1000 == 300 || o.I%1000 == 400 || o.I%1000 == 500 || o.I%1000 == 600 || o.I%1000 == 700 || o.I%1000 == 800 || o.I%1000 == 900)
		},
		func(o Operands) bool {
			return o.I == 0 || o.I%10 == 6 || (o.I%100 == 40 || o.I%100 == 60 || o.I%100 == 90)
		},
	},
}

var ordinalSet3 = &ruleSet{
	cats: []Category{One, Other},
	preds: []rule{
		func(o Operands) bool { return o.N == 1.0 },
	},
}

var ordinalSet4 = &ruleSet{
	cats: []Category{Few, Other},
	preds: []rule{
		func(o Operands) bool {
			return ((modNf(o.N, 10) == 2.0 || modNf(o.N, 10) == 3.0) && !(modNf(o.N, 100) == 12.0 || modNf(o.N, 100) == 13.0))
		},
	},
}

var ordinalSet5 = &ruleSet{
	cats: []Category{Zero, One, Few, Other},
	preds: []rule{
		func(o Operands) bool { return o.I == 0 },
		func(o Operands) bool { return o.I == 1 },
		func(o Operands) bool { return (o.I == 2 || o.I == 3 || o.I == 4 || o.I == 5 || o.I == 6) },
	},
}

var ordinalSet6 = &ruleSet{
	cats: []Category{One, Two, Few, Other},
	preds: []rule{
		func(o Operands) bool { return (o.N == 1.0 || o.N == 3.0) },
		func(o Operands) bool { return o.N == 2.0 },
		func(o Operands) bool { return o.N == 4.0 },
	},
}

var ordinalSet7 = &ruleSet{
	cats: []Category{Zero, One, Two, Few, Many, Other},
	preds: []rule{
		func(o Operands) bool { return (o.N == 0.0 || o.N == 7.0 || o.N == 8.0 || o.N == 9.0) },
		func(o Operands) bool { return o.N == 1.0 },
		func(o Operands) bool { return o.N == 2.0 },
		func(o Operands) bool { return (o.N == 3.0 || o.N == 4.0) },
		func(o Operands) bool { return (o.N == 5.0 || o.N == 6.0) },
	},
}

var ordinalSet8 = &ruleSet{
	cats: []Category{One, Two, Few, Other},
	preds: []rule{
		func(o Operands) bool { return (modNf(o.N, 10) == 1.0 && !(modNf(o.N, 100) == 11.0)) },
		func(o Operands) bool { return (modNf(o.N, 10) == 2.0 && !(modNf(o.N, 100) == 12.0)) },
		func(o Operands) bool { return (modNf(o.N, 10) == 3.0 && !(modNf(o.N, 100) == 13.0)) },
	},
}

var ordinalSet9 = &ruleSet{
	cats: []Category{One, Two, Few, Other},
	preds: []rule{
		func(o Operands) bool { return (o.N == 1.0 || o.N == 11.0) },
		func(o Operands) bool { return (o.N == 2.0 || o.N == 12.0) },
		func(o Operands) bool { return (o.N == 3.0 || o.N == 13.0) },
	},
}

var ordinalSet10 = &ruleSet{
	cats: []Category{One, Two, Few, Many, Other},
	preds: []rule{
		func(o Operands) bool { return o.N == 1.0 },
		func(o Operands) bool { return (o.N == 2.0 || o.N == 3.0) },
		func(o Operands) bool { return o.N == 4.0 },
		func(o Operands) bool { return o.N == 6.0 },
	},
}

var ordinalSet11 = &ruleSet{
	cats: []Category{One, Other},
	preds: []rule{
		func(o Operands) bool { return (o.N == 1.0 || o.N == 5.0) },
	},
}

var ordinalSet12 = &ruleSet{
	cats: []Category{Many, Other},
	preds: []rule{
		func(o Operands) bool { return (o.N == 11.0 || o.N == 8.0 || o.N == 80.0 || o.N == 800.0) },
	},
}

var ordinalSet13 = &ruleSet{
	cats: []Category{One, Many, Other},
	preds: []rule{
		func(o Operands) bool { return o.I == 1 },
		func(o Operands) bool {
			return o.I == 0 || (o.I%100 >= 2 && o.I%100 <= 20 || o.I%100 == 40 || o.I%100 == 60 || o.I%100 == 80)
		},
	},
}

var ordinalSet14 = &ruleSet{
	cats: []Category{Many, Other},
	preds: []rule{
		func(o Operands) bool {
			return modNf(o.N, 10) == 6.0 || modNf(o.N, 10) == 9.0 || (modNf(o.N, 10) == 0.0 && !(o.N == 0.0))
		},
	},
}

var ordinalSet15 = &ruleSet{
	cats: []Category{One, Many, Other},
	preds: []rule{
		func(o Operands) bool {
			return inRangeN(o.N, 1, 4) || (inRangeN(modNf(o.N, 100), 1, 4) || inRangeN(modNf(o.N, 100), 21, 24) || inRangeN(modNf(o.N, 100), 41, 44) || inRangeN(modNf(o.N, 100), 61, 64) || inRangeN(modNf(o.N, 100), 81, 84))
		},
		func(o Operands) bool { return o.N == 5.0 || modNf(o.N, 100) == 5.0 },
	},
}

var ordinalSet16 = &ruleSet{
	cats: []Category{Many, Other},
	preds: []rule{
		func(o Operands) bool {
			return (o.N == 11.0 || o.N == 8.0 || inRangeN(o.N, 80, 89) || inRangeN(o.N, 800, 899))
		},
	},
}

var ordinalSet17 = &ruleSet{
	cats: []Category{One, Two, Many, Other},
	preds: []rule{
		func(o Operands) bool { return (o.I%10 == 1 && !(o.I%100 == 11)) },
		func(o Operands) bool { return (o.I%10 == 2 && !(o.I%100 == 12)) },
		func(o Operands) bool { return ((o.I%10 == 7 || o.I%10 == 8) && !(o.I%100 == 17 || o.I%100 == 18)) },
	},
}

var ordinalSet18 = &ruleSet{
	cats: []Category{One, Two, Few, Other},
	preds: []rule{
		func(o Operands) bool { return o.N == 1.0 },
		func(o Operands) bool { return (o.N == 2.0 || o.N == 3.0) },
		func(o Operands) bool { return o.N == 4.0 },
	},
}

var ordinalSet19 = &ruleSet{
	cats: []Category{One, Other},
	preds: []rule{
		func(o Operands) bool { return inRangeN(o.N, 1, 4) },
	},
}

var ordinalSet20 = &ruleSet{
	cats: []Category{One, Two, Few, Many, Other},
	preds: []rule{
		func(o Operands) bool { return (o.N == 1.0 || o.N == 5.0 || inRangeN(o.N, 7, 9)) },
		func(o Operands) bool { return (o.N == 2.0 || o.N == 3.0) },
		func(o Operands) bool { return o.N == 4.0 },
		func(o Operands) bool { return o.N == 6.0 },
	},
}

var ordinalSet21 = &ruleSet{
	cats: []Category{One, Many, Other},
	preds: []rule{
		func(o Operands) bool { return o.N == 1.0 },
		func(o Operands) bool { return (modNf(o.N, 10) == 4.0 && !(modNf(o.N, 100) == 14.0)) },
	},
}

var ordinalSet22 = &ruleSet{
	cats: []Category{One, Other},
	preds: []rule{
		func(o Operands) bool {
			return ((modNf(o.N, 10) == 1.0 || modNf(o.N, 10) == 2.0) && !(modNf(o.N, 100) == 11.0 || modNf(o.N, 100) == 12.0))
		},
	},
}

var ordinalSet23 = &ruleSet{
	cats: []Category{Few, Other},
	preds: []rule{
		func(o Operands) bool { return (modNf(o.N, 10) == 6.0 || modNf(o.N, 10) == 9.0) || o.N == 10.0 },
	},
}

var ordinalSet24 = &ruleSet{
	cats: []Category{Few, Other},
	preds: []rule{
		func(o Operands) bool { return (modNf(o.N, 10) == 3.0 && !(modNf(o.N, 100) == 13.0)) },
	},
}

var ordinalRules = map[string]*ruleSet{
	"af":  ordinalSet0,
	"am":  ordinalSet0,
	"an":  ordinalSet0,
	"ar":  ordinalSet0,
	"as":  ordinalSet1,
	"ast": ordinalSet0,
	"az":  ordinalSet2,
	"bal": ordinalSet3,
	"be":  ordinalSet4,
	"bg":  ordinalSet0,
	"blo": ordinalSet5,
	"bn":  ordinalSet1,
	"bs":  ordinalSet0,
	"ca":  ordinalSet6,
	"ce":  ordinalSet0,
	"cs":  ordinalSet0,
	"cy":  ordinalSet7,
	"da":  ordinalSet0,
	"de":  ordinalSet0,
	"dsb": ordinalSet0,
	"el":  ordinalSet0,
	"en":  ordinalSet8,
	"es":  ordinalSet0,
	"et":  ordinalSet0,
	"eu":  ordinalSet0,
	"fa":  ordinalSet0,
	"fi":  ordinalSet0,
	"fil": ordinalSet3,
	"fr":  ordinalSet3,
	"fy":  ordinalSet0,
	"ga":  ordinalSet3,
	"gd":  ordinalSet9,
	"gl":  ordinalSet0,
	"gsw": ordinalSet0,
	"gu":  ordinalSet10,
	"he":  ordinalSet0,
	"hi":  ordinalSet10,
	"hr":  ordinalSet0,
	"hsb": ordinalSet0,
	"hu":  ordinalSet11,
	"hy":  ordinalSet3,
	"ia":  ordinalSet0,
	"id":  ordinalSet0,
	"is":  ordinalSet0,
	"it":  ordinalSet12,
	"ja":  ordinalSet0,
	"ka":  ordinalSet13,
	"kk":  ordinalSet14,
	"km":  ordinalSet0,
	"kn":  ordinalSet0,
	"ko":  ordinalSet0,
	"kw":  ordinalSet15,
	"ky":  ordinalSet0,
	"lij": ordinalSet16,
	"lo":  ordinalSet3,
	"lt":  ordinalSet0,
	"lv":  ordinalSet0,
	"mk":  ordinalSet17,
	"ml":  ordinalSet0,
	"mn":  ordinalSet0,
	"mo":  ordinalSet3,
	"mr":  ordinalSet18,
	"ms":  ordinalSet3,
	"my":  ordinalSet0,
	"nb":  ordinalSet0,
	"ne":  ordinalSet19,
	"nl":  ordinalSet0,
	"no":  ordinalSet0,
	"or":  ordinalSet20,
	"pa":  ordinalSet0,
	"pl":  ordinalSet0,
	"prg": ordinalSet0,
	"ps":  ordinalSet0,
	"pt":  ordinalSet0,
	"ro":  ordinalSet3,
	"ru":  ordinalSet0,
	"sc":  ordinalSet12,
	"scn": ordinalSet12,
	"sd":  ordinalSet0,
	"sh":  ordinalSet0,
	"si":  ordinalSet0,
	"sk":  ordinalSet0,
	"sl":  ordinalSet0,
	"sq":  ordinalSet21,
	"sr":  ordinalSet0,
	"sv":  ordinalSet22,
	"sw":  ordinalSet0,
	"ta":  ordinalSet0,
	"te":  ordinalSet0,
	"th":  ordinalSet0,
	"tk":  ordinalSet23,
	"tl":  ordinalSet3,
	"tpi": ordinalSet0,
	"tr":  ordinalSet0,
	"uk":  ordinalSet24,
	"und": ordinalSet0,
	"ur":  ordinalSet0,
	"uz":  ordinalSet0,
	"vec": ordinalSet12,
	"vi":  ordinalSet3,
	"yue": ordinalSet0,
	"zh":  ordinalSet0,
	"zu":  ordinalSet0,
}
